services:
  db:
    image: postgres
    restart: always
    ports:
      - "3307:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - mypgvolume:/var/lib/postgresql/data
volumes:
  mypgvolume: